name: Build kernel
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          apt update
          apt install -y wget zstd xz-utils make gcc flex cmake libssl-dev aria2 build-essential libelf-dev
      
      - name: Download kernel package
        run: |
          aria2c https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.7.tar.xz

      - name: Unzip Kernel
        run: |
          mv *.tar.xz kernel.tar.xz
          tar -xf kernel.tar.xz

      - name: build
        run: bash build.sh


          


      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/


