name: Build kernel
on: push

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - name: Install sudo
        run: |
          apt update
          apt install -y sudo


      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Build
        run: |
          echo "Free space:"
          df -h

      - name: Checkout
        uses: actions/checkout@v3

      - name: Disk
        run: |
          echo "Free space:"
          df -h


      - name: Setup SSH
        uses: csexton/debugger-action@master


      - name: Install Dependencies
        run: |
          apt update
          apt install -y zstd xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev aria2 build-essential libelf-dev
      
      - name: Download kernel package
        run: |
          aria2c https://mirrors.edge.kernel.org/pub/linux/kernel/v6.x/linux-6.7.tar.xz

      - name: Unzip Kernel
        run: |
          mv *.tar.xz kernel.tar.xz
          tar -xf kernel.tar.xz



      - name: build
        run: |
          cd linux-6.7/
          cp ../config .config
          scripts/config --disable DEBUG_INFO
          scripts/config --disable SYSTEM_TRUSTED_KEYS
          scripts/config --disable SYSTEM_REVOCATION_KEYS
          patch -Np1 < ../cjktty/cjktty-6.7.patch
          make -j$(($(nproc )*2)) CONFIG_FILE=../config
          make modules
          mkdir ../done
          cp ./* ../done/
          cd ..
          tar zcf kernel.tar.gz done/
          mv kernel.tar.gz artifact/


          


      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/


